### ISSUE TITLE
セミコロン抜け

### ISSUE THREAD

**Issue by arm-band** [sass-basis/basis#102]
本日イントラ内向けのテストで使わせて頂いたのですが、sassコンパイル（コマンドプロンプトからsassコマンドで）しようとしたら2箇所引っかかったのでご報告します。

1. Error: Invalid CSS after "...se-line-height)": expected "}", was "display: flex;" on line 68 of /PROJECTPATH/SCSS/basis/object/component/_drawer.scss
2. Error: Invalid CSS after "...($_color-gray))": expected "}", was "width: 0;" on line 20 of /PROJECTPATH/SCSS/basis/object/component/_select.scss

共にincludeの後ろのセミコロンが抜けていました。
それと、normalize.scssのインポートエラーも出ましたが、他の方のプルリクと同じだと思うので詳述は省きます。

**Comment by inc2734** [comment]
おお、ご報告ありがとうございます。確かにセミコロン抜けですね。なぜ僕のほうでは普通にビルドできるのでしょう…。今ガリガリアップデート中なので、ご指摘いただいた箇所も修正いれますね。

normalzize も僕のほうではコケないのですが、こちらは多分 Node や npm のバージョンによるのかなと思います。5 とか 6 であれば多分大丈夫なのではないかなと思うのですが…。

**Comment by inc2734** [comment]
あ、sass コマンドで、ということは ruby-sass になるのですかね。僕のビルド環境は gulp-sass なのでその辺の影響もあるのかもしれません。

**Comment by inc2734** [comment]
https://github.com/sass-basis/basis/commit/d1810f205bc5886e0e99bca6669fd316421ec0be

**Comment by arm-band** [comment]
早速の修正ありがとうございます。

    あ、sass コマンドで、ということは ruby-sass になるのですかね。僕のビルド環境は gulp-sass なのでその辺の影響もあるのかもしれません。

はい、さくっとテストするだけだったので、gulpは使わずruby-sassでコンパイルしました。

    normalzize も僕のほうではコケないのですが、こちらは多分 Node や npm のバージョンによるのかなと思います。5 とか 6 であれば多分大丈夫なのではないかなと思うのですが…。

あ、やはりnpmやyarnなどで引っ張ってくる運用が前提だったのですね…。
今回自分の作業範囲ではnode.js周りは全然使っていなかった（srcの中のbasisのcssとjsを持ってきただけ）ので、そもそも使い方が間違えていたということですね…。

**Comment by inc2734** [comment]
原因わかりました。gulpfile.js で、sass コンパイルする際に normalize のパスをインクルードするようにしていたのでした。なので自力でコンパイルするときはこの部分を自分で設定しないとですね。
https://github.com/sass-basis/basis/blob/56d6d9cfbc8ef15971200476420e095b3a3f7595/gulpfile.js#L51
Basis の gulpfile.js を自分のプロジェクト内にコピーし不要な部分を削って使うのが一番簡単かなと。アップデート作業が落ち着いたらスターターキット的なリポジトリも作ろうとは思っているのですが。。
