### ISSUE TITLE
sanitize.css

### ISSUE THREAD

**Issue by inc2734** [sass-basis/basis#38]
basis のブラウザサポートは IE10 以上としているので、normalize.css より sanitize.css のほうがあっているかも？
https://10up.github.io/sanitize.css/

**Comment by torounit** [comment]
好みの世界ではありますけど、wordpress 屋さんとしては 10up 製の sanitize を押したいですよね。

**Comment by torounit** [comment]
あと、公式が sass とか提供してるのもメンテが楽になるはず。

**Comment by torounit** [comment]
これ 2.0.0 に含めます？プルリクmergeしてもらえば結構さくっといけます−

**Comment by inc2734** [comment]
ふくめましょう！

**Comment by torounit** [comment]
了解です！

**Comment by torounit** [comment]
https://github.com/10up/sanitize.css/blob/master/sanitize.css#L123-L127

みたいなCSS有りますけどどうします？ちょっと、リセット周りがあってくどそう。

**Comment by inc2734** [comment]
あーこれはいやですね。まぁどうせ _base.scss で余白は再設定してるんですけど…。保留しましょう！

**Comment by torounit** [comment]
了解です。ちょっと 全称セレクタは地雷のにおいがしました。
