### ISSUE TITLE
The need for modifiers of the ._c-row

### ISSUE THREAD

**Issue by inc2734** [sass-basis/basis#62]
_c-row--md-left とか、_c-row--md-top とか位置系のモディファイアは果たして本当に必要なのか。ブレイクポイント毎に左寄せ右寄せとか、上寄せ下寄せを切り替えることはほとんど無い気が…。これ消せばサイズも結構減らせるメリットも。

**Comment by torounit** [comment]
CSSのサイズはたかがしれてるのであんまり気にしなくても良いとは思います。
ただ、あんまり見たことは無いですねぇ。
ブレイクポイント枚にそこの切り替えが必要なケースは設計に失敗してる感有るけど。

無くてもまぁ良いのかなー程度ですね。積極的に無くすべきというわけでは無いですけど、互換性と保守の問題ですね。

**Comment by inc2734** [comment]
flexboxgrid、FOX CSS という flexbox グリッドシステムのフレームワークを見たときはブレイクポイント毎に切り替えれるようになっていたっぽかったので、先人がそうしているならいいや、とそのままにしています。

> ブレイクポイント枚にそこの切り替えが必要なケースは設計に失敗してる感有るけど。

そうなんですよね。だから削りたいのもあります。
