### ISSUE TITLE
 .css also should be included in the repository ?

### ISSUE THREAD

**Issue by inc2734** [sass-basis/basis#63]
リポジトリに .css は含まれていないので、Gulp の環境が作れない人は簡単に使うことができない。結構致命的だと思うので .css もリポジトリに含めて、リリース時だけ .css もコミットするとかしたほうが良いかも。

**Comment by torounit** [comment]
レポジトリには含めなくても良いのかなーとは思っては居ますが、どうなんでしょう。npm の名前も sass って入ってるし。releaseブランチに css を入れるのなどは有りなのかなとは思ったりします。

**Comment by inc2734** [comment]
ミスりまくってコミット履歴があれてしまいましたが、とりあえず release というブランチに .css を含めたデータを自動プッシュするようにしました。でも、調べたところ release はリリースの準備をするためのブランチで、コンパイルしたデータとかは master に置くものっぽいので、後々そのように変更しようかなぁと思っています。

**Comment by torounit** [comment]
なんだと・・・。
develop ブランチは綺麗にしておいて、master はってことですか。なるほど、自動ビルドも npm 限定ですしねぇ。
（masterにプルリク来る地獄が見えた）

**Comment by inc2734** [comment]
> masterにプルリク来る地獄が見えた

あ…。確かに(TT) となると現状の release ブランチのほうがアリかもですねぇ。

**Comment by torounit** [comment]
あ、githubフローとか参照した方が良いかも。http://qiita.com/tbpgr/items/4ff76ef35c4ff0ec8314
