### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by inc2734** [sass-basis/basis#76]
変数・関数・ミックスインの命名規則をなぜか -（ハイフン）つなぎにしてたけど、エディタで選択しにくいので _（アンダースコア）区切りのほうが良くないか…。
Sass の場合「-」と「_」は同一視されるので後方互換性的には問題ないし…

**Comment by torounit** [comment]
cssそのものがハイフンケースなので、CSSのプロパティ代わりに扱いたいようなmixinとかがつらくなるかも

**Comment by inc2734** [comment]
それは思いました!! でも v4 に向けての構造変更でそういうミックスインは使いづらくなるかなぁとか思ってるのでちょっと検討中…
