### ISSUE TITLE
$bs-font-size when $bs-use-mixin-only: true

### ISSUE THREAD

**Issue by inc2734** [sass-basis/basis#79]
`$bs-use-mixin-only` が `false` のとき（デフォルト）、`$bs-font-size` は 1.6rem で 16px 相当となるけど、`$bs-use-mixin-only` が `true` のときは foundation 層の CSS も読み込まれないため `$bs-font-size` が 1.6rem だと 25.6px 相当となってしまう。

**Comment by kngsmym** [comment]
こちらのissueは僕の質問に端を発するのだと思いますが、現バージョンで確認したところ$bs-use-mixin-only が trueの場合はfoundation/_base.scssの中身は全く読み込まれないので、$bs-font-sizeを参照してのベースフォントサイズ指定もされず、基本のフォントサイズが16px * 1.6rem = 25.6pxとなる現象は起こっていないように思います。

僕がこの質問をした際の動作確認にそもそもなにか勘違いがあったのだと思います。申し訳ありません。

Basisのfoundation層のCSSを使わないなら、
```
html{
font-size:62.5%;
}
```
などの指定もユーザー側で行う必要があり、僕がそれをやってなかっただけという話しなのかなと。

そうすると別チャットでお話した、

> 「Basis の CSS は使いたくない」という人は html { ... } という CSS が勝手に追加されるのもイヤだと思うんです。

という点を考慮すると、$bs-use-mixin-only を trueにする場合はベースサイズの調整なんかも全部自分でやりましょう（foundation層は提供しませんよ）スタンスとなり、この件に関する対応としては特に手を加える必要が無いように思いました。

ただしmixinで$bs-font-sizeを参照して動作するものがあれば、それは個人のベースフォントとは別にBasisの設定サイズを参照して動くので、$bs-font-sizeはちゃんと調整してねって話になるんでしょうか。

すいません。その辺はまだよくわかってないですがなんとなく書きました。

**Comment by inc2734** [comment]
コメントありがとうございます！！！！

> $bs-font-sizeを参照してのベースフォントサイズ指定もされず、基本のフォントサイズが16px * 1.6rem = 25.6px となる現象は起こっていないように思います。

えと、ご指摘の通り、基本のフォントサイズはユーザーが書いた CSS がベースになるので確かに 25.6px にはなりません。が、`$bs-font-size` は Basis を mixin ライブラリして使用した時にもデザインのバランスが整うようにするために mixin や function の内部でも使われており、そのときに 25.6px 相当と計算されてしまうとバランスが崩れてしまう、また、ユーザーが全体のバランスを整えるために各所で自分で font-size を指定せずに `$bs-font-size` を利用した場合におかしなことになることを懸念し isssue をたてました。

https://github.com/sass-basis/basis/blob/master/src/scss/core/mixin/component/_btn.scss
https://github.com/sass-basis/basis/blob/master/src/scss/core/mixin/helper/_typography.scss

ただ、この懸念は未検証であり、`$bs-use-mixin-only` が `true` のときに `$bs-font-size` が 1rem になっていなくても実は特に問題ないという可能性もあると思います。検証してから issue 立てろよ！という話なのですが、僕自身 `$bs-use-mixin-only: true` で使ったことがなく、そうした使い方をしているユーザーさんから、実際不便はないのかというご意見を頂ければという思いもあったりします。

**Comment by kngsmym** [comment]
ご返答ありがとうございます。
今回、flexboxでグリッドにするのにBasisを利用させてもらったので僕も他のmixinは未検証なのですが、今後使ってみてまたお話させてください！

**Comment by inc2734** [comment]
なるほど！実は、グリッド間の余白は行間の大きさである `$bs-base-line-height` が基準になっているのですが、`$bs-base-line-height` の算出にはは `$bs-font-size` が使われたりしていますw
https://github.com/sass-basis/basis/blob/master/src/scss/core/mixin/component/_row.scss
https://github.com/sass-basis/basis/blob/master/src/scss/core/variable/_typography.scss

**Comment by kngsmym** [comment]
あーそのあたり詳しく見てみます。

自分のサイトのときはデザインを起こさず、まずフレームワークなどで骨組み作ってそれにデザインを当てたり、ボックスを入れ替えたりなどで構築していくので、今のところ完全Basisまかせでグリッド間を気にしてませんでした。（逆に言えばいい感じの余白になっている状態なのかと）

ちょっとその辺調整してみたりしますね。

**Comment by inc2734** [comment]
ん、あれ、すみません、僕の勘違いでした…。余白をとるための仕組みとして mixin は用意していますが、グリッドの mixin の中では使ってなかったみたいです。。

なにか気づいた時にでもまた書き込んでいただければ！

**Comment by kngsmym** [comment]
承知しました！

**Comment by inc2734** [comment]
そもそも、Basis の foundation レイヤーで `html { font-size:62.5%; }` してるからこのようなことを考えなくてはいけなくなっている気がするので、`html { font-size:62.5%; }` を削除し、`$bs-font-size: 1rem` とするのが素直な気がする。
