### ISSUE TITLE
bs-bounce-scale-#{$suffix} Invalid Name Error

### ISSUE THREAD

**Issue by segayuu** [sass-basis/basis#83]
初Issues失礼します。
NetBeans8.1を用いてサイト制作していたのですが、Basis v5.0.0でのcss出力時にエラーが出ておりました。

`@keyframes bs-bounce-scale-110.0 {(ry)}`

理由はcss出力時にbs-strip-unitによって'.'が入り込んでいて、それは識別子として使用不可な文字だからです。
[@keyframeの定義](https://developer.mozilla.org/ja/docs/Web/CSS/@keyframes)
[CSS識別子の定義](http://momdo.s35.xrea.com/web-html-test/spec/CSS21/syndata.html#value-def-identifier)
ブラウザ上では問題ないのですがそのためだけにエラーを手動で潰すのは少し面倒ですし、衛生的に少しよろしくありません。
ご確認と可能であれば修正、よろしくおねがいします。

**Comment by segayuu** [comment]
すみません、glupなしで直にsassを実行したためみたいですorz

[percentage()で小数点以下を切り捨てる指定方法【Sass】](http://blog.e-riverstyle.com/2012/10/percentagesass.html)
とりあえずsass単体でも、ページ内容に合わせて変更を行ったらエラーは発生しませんでした。

**Comment by inc2734** [comment]
なるほどです。情報ありがとうございます！
